version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels:
      - dependencies
      - automerge
    commit-message:
      prefix: deps
